linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - decorder
    - dupl
    - errorlint
    - exhaustive
    - forcetypeassert
    - goconst
    - godot
    - prealloc
    - nilerr
    - predeclared
    - unconvert
    - wrapcheck
    - staticcheck
    - dupl
    - gocritic
